#!/usr/bin/env bash

working_dir=$(dirname "$0")

target="${working_dir}/include.gitconfig"

echo "# This file is automatically generated. Please do not edit directly" > "${target}"
echo "" >> "${target}"

if (ls "${working_dir}"/gitconfig.d/*.gitconfig >/dev/null 2>&1)
then
    echo "[include]" >> "${target}"
    for config_file in "${working_dir}"/gitconfig.d/*.gitconfig
    do
        filename=$(basename "${config_file}")
        echo "    path = gitconfig.d/${filename}" >> "${target}"
    done
fi

